name: Deploy MARP Slides to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Se activa al hacer push a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install MARP CLI
        run: npm install -g @marp-team/marp-cli

      - name: Convert MARP to HTML
        run: marp presentacion.md -o index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./